Webcfg logreduction
xmidt-org/webcfg pull request #100
Opened 2021-11-22 17:17 UTC by krishnangnair

To Reduce the Info level logging

2021-11-23 08:52 UTC, sadhyama requested changes

2021-11-23 08:52 UTC, sadhyama commented on src/webcfg_event.c
> +					WebcfgDebug("ACK EVENT: %s,%lu,%lu,ACK,%lu %s\n", eventParam->subdoc_name,(long)eventParam->trans_id, (long)eventParam->version, (long)eventParam->timeout, "(doc apply success)");
Retain line 304, 305 as INFO , these are added from this PR https://github.com/xmidt-org/webcfg/pull/20/files to match the logging same as AC as per QA bug request RDKB-30021 .

Please check all logs in event.c that we are not removing any log line from above mentioned PR as these are required logging for telemetry purpose.

2021-11-23 08:52 UTC, sadhyama commented on src/webcfg_event.c
> +					WebcfgDebug("doc apply need time, start timer.\n");
This is required log.

2021-11-23 08:52 UTC, sadhyama commented on src/webcfg_event.c
> +						WebcfgDebug("COMP_INIT EVENT: %s,%d,%lu\n", eventParam->subdoc_name,0, (long)eventParam->version);
449 and 454 are also required.

2021-11-23 08:52 UTC, sadhyama commented on src/webcfg_multipart.c
> +						WebcfgDebug("Content-Type is multipart/mixed. Valid\n");
This is required log.

2021-11-23 08:52 UTC, sadhyama commented on src/webcfg_multipart.c
> +						WebcfgDebug("failure_reason %s\n",errDetails);
Retain this log as it is used for telemetry as per RDKB-35530

2021-11-23 08:52 UTC, sadhyama commented on src/webcfg_timer.c
> +		WebcfgDebug("Maintenance time is equal to current time\n");
Better to keep this log to see maintenance timestamp in webcfg

2021-11-23 08:58 UTC, sadhyama commented on src/webcfg.c
> -	WebcfgInfo("B4 pthread_exit\n");
I think we can enable this log as this will log only once during RFC disable case , this log also confirms no stuck issues at other threads.

2021-11-23 09:42 UTC, krishnangnair commented on src/webcfg_multipart.c
> +						WebcfgDebug("failure_reason %s\n",errDetails);
Ok done the changes

2021-11-23 09:47 UTC, krishnangnair commented on src/webcfg.c
> -	WebcfgInfo("B4 pthread_exit\n");
ok

2021-11-23 09:48 UTC, krishnangnair commented on src/webcfg_db.c
> +			WebcfgDebug("doc %s is updated to version %lu status %s error_details %s error_code %lu trans_id %lu temp->retry_count %d\n", docname, (long)temp->version, temp->status, temp->error_details, (long
ok

2021-11-23 11:42 UTC, krishnangnair commented
To execute guardrails again.

2021-11-23 11:51 UTC, krishnangnair commented on src/webcfg_metadata.c
> +					strncpy(sdInfo->support,subtoken,(sizeof(sdInfo->support)-1));//To handle subtoken null case
resolved

2021-11-23 11:55 UTC, krishnangnair commented
To execute guardrails again.

2021-11-23 11:58 UTC, sadhyama approved these changes

2021-11-24 18:17 UTC, shilpa24balaji commented on src/webcfg_metadata.c
> +				if(subtoken != NULL)
Should this check be at Line 140?

2021-11-25 06:37 UTC, merged