Optimise the TR181 GET/SET handler in webconfig.
xmidt-org/webcfg pull request #107
Opened 2021-12-08 11:54 UTC by Sreedevi29

2021-12-08 13:04 UTC, sadhyama requested changes

2021-12-08 13:04 UTC, sadhyama commented on src/webcfg_rbus.c
> +        WebcfgError("Unexpected parameter = %s\n", paramName); //free paramName req.?
Please check if this need to be freed

2021-12-08 13:04 UTC, sadhyama commented on src/webcfg_rbus.c
> +    propertyName = strdup(rbusProperty_GetName(property));
propertyName need to be freed. I think we need to add free for propertyName , paramName in multiple get/set handlers e.g. line 316, 383 etc.

2021-12-16 06:47 UTC, sadhyama requested changes

2021-12-16 06:47 UTC, sadhyama commented on src/webcfg_rbus.c
> +        WebcfgError("Unexpected parameter = %s\n", paramName); //free paramName req.?
If not required to free, remove this comment too

2021-12-16 06:47 UTC, sadhyama commented on src/webcfg_rbus.c
> +        WebcfgError("Unexpected parameter = %s\n", paramName); //free paramName req.?
Remove this comment

2021-12-16 06:47 UTC, sadhyama commented on src/webcfg_rbus.c
> +    WebcfgDebug("Inside webcfgFrSetHandler\n");
Try to reduce this Inside , End debug logs in each function

2021-12-16 06:52 UTC, sadhyama requested changes

2021-12-16 06:52 UTC, sadhyama commented on src/webcfg_rbus.c
> + * Data get handler for Webpa parameters
Change it to Webconfig or remove this .

2021-12-16 06:55 UTC, sadhyama commented on src/webcfg_rbus.c
> +                retPsmGet = RBUS_ERROR_BUS_ERROR;
Remove this error code assigning for psm DB get.

2021-12-16 08:27 UTC, sadhyama approved these changes

2021-12-16 18:18 UTC, shilpa24balaji commented on src/webcfg_rbus.c
> +		isRfc = false;
is this needed when default is false?

2021-12-16 18:25 UTC, merged