Subscribed to CurrentActiveInterface value change event
xmidt-org/webcfg pull request #125
Opened 2022-03-21 13:17 UTC by Thanusha-D

2022-03-24 06:11 UTC, sadhyama requested changes

2022-03-24 06:11 UTC, sadhyama commented on src/webcfg_rbus.c
> +	      WebcfgInfo("Device.X_RDK_WanManager.CurrentActiveInterface subscribe failed : %d\n", rc);
Change this to WebcfgError log . Also better to use WEBCFG_INTERFACE_PARAM macro itself instead of hardcoding TR181 param in log

2022-03-24 06:11 UTC, sadhyama commented on src/webcfg_multipart.c
> +void get_webCfg_interface(char **interface);
get_webCfg_interface could be static itself right ?, as we are not using this func anywhere outside webcfg_multipart.c.

2022-03-24 06:57 UTC, Thanusha-D commented on src/webcfg_multipart.c
> +void get_webCfg_interface(char **interface);
get_webCfg_interface  is throwing error when WAN failover flag enabled, as function defined but not used, if it is defined as static. In wan failover case this function won't be called so throwing that error. That's why made it as a normal void function.

2022-03-24 06:58 UTC, Thanusha-D commented on src/webcfg_rbus.c
> +	      WebcfgInfo("Device.X_RDK_WanManager.CurrentActiveInterface subscribe failed : %d\n", rc);
made the change

2022-03-24 07:23 UTC, sadhyama commented on src/webcfg_multipart.c
> +void get_webCfg_interface(char **interface);
ok

2022-03-24 08:19 UTC, sadhyama approved these changes

2022-03-25 18:25 UTC, shilpa24balaji commented on src/webcfg_rbus.c
> +        WebcfgInfo("   Old Value: %s\n", rbusValue_GetString(oldValue, NULL));
Instead of 4 info logs try to keep one info log with all the information

2022-03-25 18:33 UTC, shilpa24balaji requested changes

2022-03-25 18:33 UTC, shilpa24balaji commented on src/webcfg_rbus.c
> +  WebcfgInfo("subscribeHandler called:  error val=%d\n", error);
Log subscription->eventName and rbusError_ToString(error)

2022-03-25 18:33 UTC, shilpa24balaji commented on src/webcfg_rbus.c
> +	WebcfgInfo("New Interface value g_interface = %s\n",get_global_interface());
Instead of 4 info logs try to keep one info log with all the information

2022-03-25 18:33 UTC, shilpa24balaji commented on src/webcfg_rbus.c
> +      WebcfgInfo("Subscribing to Device.X_RDK_WanManager.CurrentActiveInterface Event\n");
change to debug

2022-03-25 18:33 UTC, shilpa24balaji commented on src/webcfg_rbus.c
> +	      WebcfgError("%s subscribe failed : %d\n",WEBCFG_INTERFACE_PARAM, rc);
Log rbusError_ToString(rc)

2022-03-28 05:29 UTC, Thanusha-D commented on src/webcfg_rbus.c
> +  WebcfgInfo("subscribeHandler called:  error val=%d\n", error);
done changes

2022-03-28 10:46 UTC, shilpa24balaji commented on src/webcfg_rbus.c
> +	      WebcfgError("%s subscribe failed : %s\n", WEBCFG_INTERFACE_PARAM, rbusError_ToString(rc));
Log rc and rbusError_ToString(rc)

2022-03-28 10:56 UTC, shilpa24balaji commented on src/webcfg_rbus.c
> +static void subscribeHandler(
Should this be renamed?

2022-03-29 13:24 UTC, merged