CLI Multipart Blob Decoder Utility
xmidt-org/webcfg pull request #132
Opened 2022-07-07 08:11 UTC by guruchandru

2022-07-12 08:33 UTC, sadhyama commented on src/webcfg_multipart.c
> +			printf("Len is %d\n", *len);
Printfs change to WebcfgDebug - lines 2492, 2493 , 855 , 856 etc

2022-07-12 08:54 UTC, sadhyama commented on src/webcfg_rbus.c
> +	WebcfgInfo("send RBUS_ERROR_SUCCESS\n");
Better to log along with methodName as other blob output will go to device console

2022-07-12 11:20 UTC, sadhyama commented on src/webcfg_rbus.c
> +		if((valueString != NULL) && (strcmp(valueString,"") == 0))
Here strlen > 0 check we can add and return RBUS_ERROR_INVALID_INPUT and for empty doc with space " " case , we can allow as it will return RBUS_ERROR_ELEMENT_DOES_NOT_EXIST when doc not found in cache.

2022-07-14 10:02 UTC, guruchandru commented on src/webcfg_rbus.c
> +	rbusObject_fwrite(inParams, 1, stdout);
commented

2022-07-14 10:03 UTC, guruchandru commented on src/webcfg_multipart.c
> +			printf("Len is %d\n", *len);
changed to debug logs

2022-07-14 10:03 UTC, guruchandru commented on src/webcfg_rbus.c
> +	WebcfgInfo("send RBUS_ERROR_SUCCESS\n");
Resolved in recent tag

2022-07-14 10:06 UTC, guruchandru commented on src/webcfg_rbus.c
> +		if((valueString != NULL) && (strcmp(valueString,"") == 0))
resolved in recent change used strlen check for empty doc

2022-07-14 10:07 UTC, guruchandru commented on src/webcfg_rbus.c
> +		valueString = strdup(rbusValue_GetString(propValue, &len));
removed strdup

2022-07-18 06:31 UTC, sadhyama commented on src/webcfg_rbus.c
> +		if(!(strlen(valueString) > 0))
add null check for valueString and strlen of 0 check is good enough here , 
if((valueString != NULL) && (strlen(valueString) == 0))

2022-07-19 03:13 UTC, sadhyama approved these changes

2022-07-25 09:27 UTC, shilpa24balaji commented on src/webcfg_multipart.c
> +int fetchMpBlobData(char *docname, void **blobdata, int *len, uint32_t *etag)
Move this to rbus.c and under the bin flag. Use the enum error

2022-07-26 09:44 UTC, sadhyama commented on src/webcfg_rbus.c
> +	switch(e)
Better to add a default case also as "unknown error" , else errorstring will become NULL while doing rbusValue_SetString

2022-07-26 09:45 UTC, sadhyama commented on src/webcfg_rbus.c
> +		free(errorString);
Add a NULL check here before free

2022-07-26 09:46 UTC, sadhyama commented on src/webcfg_rbus.c
> +		WebcfgInfo("The errorCode is %d\n", errorCode);
Log errorcode and errorsting in a single line

2022-07-26 09:55 UTC, sadhyama requested changes

2022-07-26 09:55 UTC, sadhyama commented on src/webcfg_rbus.c
> +			WebcfgError("The subdoc name is not valid\n");
line 929 and 936 logs same error which will be difficult during debugging, use different error logs such as "subdoc value is NULL" , "subdoc value is empty" in each cases .( anyway in errorstring we are logging invalid input ).

2022-07-26 12:00 UTC, sadhyama approved these changes

2022-07-26 14:38 UTC, merged