#RDKC-11869,RDKC-11985: Resolve build issues with existing opensource
xmidt-org/webcfg pull request #135
Opened 2022-08-23 16:02 UTC by relangovan

Reason for change: 1)Upgraded parodus components to 2.0.0v
                   2)Added cpeabs repo for RDKC tr181 params
                   3)Created webconfig bin and added service
Test Procedure: Webcfg binary must be running
Risks: Low

Signed-off-by: relangovan <Revathy_Elangovan@comcast.com>

2022-08-23 16:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/xmidt-org/webcfg?pullRequest=135) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/xmidt-org/webcfg?pullRequest=135) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/xmidt-org/webcfg?pullRequest=135) it.</sub>

2022-08-23 18:56 UTC, karuna2git requested changes

2022-08-23 18:56 UTC, karuna2git commented on src/webcfg_multipart.c
>  size_t writer_callback_fn(void *buffer, size_t size, size_t nmemb, struct token_data *data)
as per the spec the https://curl.se/libcurl/c/CURLOPT_WRITEFUNCTION.html

> #include <curl/curl.h>
> 
> size_t write_callback(char *ptr, size_t size, size_t nmemb, void *userdata);
> CURLcode curl_easy_setopt(CURL *handle, CURLOPT_WRITEFUNCTION, write_callback);

The userData must be void*.

Please remove the macro and use the new function header itself as default for all

2022-08-23 18:56 UTC, karuna2git commented on rdk_env.xml
> +     <dependencies>sdk,curl,cjson,rbus,libsyswrapper,libexchanger,webconfig-framework</dependencies>
sdk,curl, rbus,libsyswrapper  is good enough

2022-08-23 18:56 UTC, karuna2git commented on rdk_build.sh
> +if [ "$XCAM_MODEL" == "SCHC2" ]; then
Line 47 to 55 is not needed

2022-08-23 18:56 UTC, karuna2git commented on rdk_build.sh
> +if [ "$XCAM_MODEL" == "SCHC2" ]; then
define a generic macro; not specific to Devices. Something like,
```
    export CC=${SOURCETOOLCHAIN}gcc
    export CXX=${SOURCETOOLCHAIN}g++
    export GXX=${SOURCETOOLCHAIN}g++
    export AR=${SOURCETOOLCHAIN}ar
    export LD=${SOURCETOOLCHAIN}ld
    export STRIP=${SOURCETOOLCHAIN}strip
```

2022-08-23 18:56 UTC, karuna2git commented on rdk_build.sh
> +      export LDFLAGS+="-L${RDK_PROJECT_ROOT_PATH}/opensource/lib -lmsgpackc -lcjson -lcurl -lcimplog -ltrower-base64 -lwdmp-c -lwrp-c -llinenoise -L${RDK_PROJECT_ROOT_PATH}/rdklogger/src/.libs -lrdkl
Remove the LDFLAGS.
The CMakelist.txt of webcfg shd be able to link all the needed library for it.
all you have to do is to define rpath

Ex: Add the below into CMAKE command at cmake; ie Line#123
```-DCMAKE_EXE_LINKER_FLAGS="-Wl,-rpath-link,${RDK_FSROOT_PATH}/usr/lib"```

2022-08-23 18:57 UTC, karuna2git requested changes
Please refer my comment in the changeset

2022-08-24 15:19 UTC, relangovan commented
Will create a new pull request after incorporating the review comments.

2022-08-24 15:19 UTC, closed without merging