Maintenance Timer TZ Offset Fix
xmidt-org/webcfg pull request #154
Opened 2023-05-03 10:35 UTC by guruchandru

2023-05-09 10:51 UTC, sadhyama requested changes

2023-05-09 10:51 UTC, sadhyama commented on src/webcfg_generic.c
> +long getTimeOffset(void)
Add this func in generic_pc.c and also confirm local pc build is successful

2023-05-09 13:33 UTC, guruchandru commented on src/webcfg_generic.c
> +long getTimeOffset(void)
changes are done and no local build issues seen

2023-05-10 08:23 UTC, sadhyama requested changes

2023-05-16 11:25 UTC, merged