Fix:memory leak during forcesync
xmidt-org/webcfg pull request #229
Opened 2024-07-18 15:00 UTC by nlrcomcast

[Field][TCXB7|TCXB8][7.3p3s1] webconfig memory is leaking with uptime

2024-07-19 06:51 UTC, sadhyama commented on src/webcfg_multipart.c
> +		WebcfgInfo("Deleted mp node: temp->name_space:%s\n", temp->name_space);
Move it to Debug after testing

2024-07-19 06:53 UTC, sadhyama requested changes

2024-07-19 06:53 UTC, sadhyama commented on src/webcfg_db.c
> +	WebcfgInfo("Delete node--> temp->name %s temp->version %lu temp->status %s temp->isSupplementarySync %d temp->error_details %s temp->error_code %lu temp->trans_id %lu temp->retry_count %d temp->clou
Move it to Debug after testing

2024-07-22 07:02 UTC, nlrcomcast commented on src/webcfg_multipart.c
> +		WebcfgInfo("Deleted mp node: temp->name_space:%s\n", temp->name_space);
done

2024-07-22 07:02 UTC, nlrcomcast commented on src/webcfg_db.c
> +	WebcfgInfo("Delete node--> temp->name %s temp->version %lu temp->status %s temp->isSupplementarySync %d temp->error_details %s temp->error_code %lu temp->trans_id %lu temp->retry_count %d temp->clou
done

2024-07-22 07:45 UTC, sadhyama approved these changes

2024-07-22 07:47 UTC, merged