webconfig metadata parsing and processing
xmidt-org/webcfg pull request #28
Opened 2020-08-21 12:17 UTC by guruchandru

2020-08-26 15:01 UTC, sadhyama approved these changes

2020-08-26 17:35 UTC, shilpa24balaji commented on src/webcfg_metadata.h
> +#define MAX_SUBDOCS_SIZE 24
Delete these macros MAX_GROUP_SIZE and MAX_SUBDOCS_SIZE as its not used

2020-08-26 17:37 UTC, shilpa24balaji commented on src/webcfg_multipart.c
> +static char g_supportedDocs[512] ={'\0'};
supported_bits is dynamic, then why is this g_supportedDocs[512] fixed array?

2020-08-26 17:55 UTC, shilpa24balaji requested changes

2020-08-26 17:55 UTC, shilpa24balaji commented on src/webcfg_multipart.c
> +		supportedDocs_header = (char *) malloc(sizeof(char)*MAX_BUF_SIZE);
Why is malloc for MAX_BUF_SIZE 256 when the length of the doc header is known? Cases when the header is long this will fail

2020-08-26 17:55 UTC, shilpa24balaji commented on src/webcfg_multipart.c
> +			snprintf(supportedDocs_header, MAX_BUF_SIZE, "X-System-Supported-Docs: %s", g_supportedDocs);
g_supportedDocs is not needed, supported_bits can used directly

2020-08-26 17:55 UTC, shilpa24balaji commented on src/webcfg_multipart.c
> +								snprintf(result,MAX_VALUE_LEN,"crash_retrying:%s", errDetails);
Thinking set_doc_fail(1); should be in this else block so we dont trigger retry for unsupported case. So if all are unsupported docs then retry will not be attempted.

2020-08-27 10:01 UTC, shilpa24balaji commented on src/webcfg_multipart.c
> +			WebcfgInfo("Retry skipped for %s (%s)\n",temp->name,temp->error_details);
change this to debug

2020-08-27 10:03 UTC, shilpa24balaji approved these changes

2020-08-27 11:54 UTC, merged