Fix for root update
xmidt-org/webcfg pull request #30
Opened 2020-09-04 14:55 UTC by guruchandru

2020-09-07 08:38 UTC, sadhyama requested changes

2020-09-07 08:38 UTC, sadhyama commented on src/webcfg_multipart.c
> +							WebcfgInfo("the retry flag value is %d\n", get_doc_fail());
Once all docs are success and root is updated, make sure it is not going to for loop to process again. So in this 204 case add break to for loop once root is updated and mp cache is freed.

2020-09-08 06:38 UTC, shilpa24balaji commented on src/webcfg_multipart.c
> +							if(checkRootUpdate() == WEBCFG_SUCCESS)
Lets move this root check inside the 204 case or at the end of multipart processing after aker

2020-09-08 08:10 UTC, shilpa24balaji commented on src/webcfg_multipart.c
> +							if(checkRootUpdate() == WEBCFG_SUCCESS)
You can add check (ccspStatus == 204 && subdocStatus != WEBCFG_SUCCESS) also here so its only for unsupported case

2020-09-08 11:00 UTC, shilpa24balaji commented on src/webcfg_multipart.c
> +							WebcfgInfo("checkRootUpdate\n");
Remove this log

2020-09-08 11:03 UTC, shilpa24balaji commented on src/webcfg_multipart.c
> +								WebcfgInfo("updateRootVersionToDB\n");
Is this info log needed?

2020-09-08 11:42 UTC, sadhyama approved these changes

2020-09-08 12:19 UTC, merged