Business logic to decide and choose the Bus API to use for BLOB SET
xmidt-org/webcfg pull request #86
Opened 2021-10-27 06:49 UTC by Sreedevi29

2021-11-11 09:31 UTC, sadhyama requested changes

2021-11-11 09:31 UTC, sadhyama commented on src/webcfg_event.c
> +							appended_doc = webcfg_appendeddoc( gmp->name_space, gmp->etag, pm->entries[i].value, pm->entries[i].value_size, &doc_transId, &sendMsgsize);
Business logic need to be added during blob retry also here,  currently setValues is used during retry cases. ,
https://github.com/xmidt-org/webcfg/blob/22fa82854e91ecf3d0b5b3feace066bd8d190753/src/webcfg_event.c#L1005

2021-11-15 10:28 UTC, shilpa24balaji commented on src/webcfg_multipart.c
> +		void *buff = NULL;
Move this declaration after line 685 where ifdef is defined

2021-11-17 07:04 UTC, sadhyama approved these changes

2021-11-17 07:28 UTC, shilpa24balaji commented on src/webcfg_event.c
>  							WebcfgDebug("appended_doc length: %zu\n", strlen(appended_doc));
When rbus listener support is true strlen on binary data will not give correct results

2021-11-17 07:31 UTC, shilpa24balaji commented on src/webcfg_event.c
> +									buff = reqParam[i].value;
reqParam set is not needed in this case. buff can be just set to appended_doc

2021-11-17 07:46 UTC, shilpa24balaji commented on src/webcfg_multipart.c
> +									buff = reqParam[i].value;
I feel reqParam set is not needed here

2021-11-17 10:17 UTC, shilpa24balaji commented on src/webcfg_metadata.c
> +			if(strncmp(sd->rbus_listener, "true", strlen("true")) == 0)
add null check for rbus_listener

2021-11-17 10:53 UTC, shilpa24balaji commented on src/webcfg_metadata.c
> +			if( sd->dest != NULL)
dest is char[] so NULL check is not applicable

2021-11-17 12:31 UTC, merged