Move connected client notification business logic from webconfig to w…
xmidt-org/webcfg pull request #97
Opened 2021-11-19 12:53 UTC by Sreedevi29

…ebpa.

2021-11-22 13:28 UTC, shilpa24balaji commented on src/webcfg_event.c
> +									WebcfgDebug("rbus_set success for mesh/cujo\n");
Lets enable this Info log and add rbus_set success for Device.X_RDK_Webpa.ConnectedClientNotify parameter

2021-11-22 13:28 UTC, shilpa24balaji commented on src/webcfg_event.c
> +									WebcfgDebug("rbus_set failed for mesh/cujo\n");
Enable this error log

2021-11-23 08:12 UTC, sadhyama requested changes

2021-11-23 08:12 UTC, sadhyama commented on src/webcfg_event.c
>  					//Based on ACK event if mesh/cujo is enabled then connected client notification need to be turned OFF
Dont add bin check here, I feel better to add bin changes only inside handleConnectedClientNotify function.

2021-11-23 08:12 UTC, sadhyama commented on src/webcfg_event.c
> +						char tmpStr[32] = {'\0'};
Move this code inside handleConnectedClientNotify function so that main case loop doesnot look complex as per existing flow.

2021-11-23 08:12 UTC, sadhyama commented on src/webcfg_event.c
> -void handleConnectedClientNotify(char *status)
Retain handleConnectedClientNotify function as it is for distro off cases.

2021-11-23 09:08 UTC, sadhyama commented on src/webcfg_event.c
> +						WebcfgError("setAttributes/rbus_set failed for parameter : %s ret: %d\n", attArr[0].name, ret);
Here attArr can be NULL

2021-11-23 09:14 UTC, sadhyama commented on src/webcfg_event.c
> +						attArr[0].name = strdup("Device.X_RDK_Webpa.ConnectedClientNotify");
@shilpa24balaji This parameter name should we fetch from parodus2ccsp code similar to connected client parameter from getConnClientParamName() function, as this parameter may not be applicable for rdkv/other platforms?

2021-11-23 10:29 UTC, sadhyama commented on src/webcfg_event.c
> +						attArr[0].name = strdup("Device.X_RDK_Webpa.ConnectedClientNotify");
As we discussed, fetch this parameter name from rdkb specific code from cpeabs override function instead of hardcoding in webcfg . 
https://github.com/xmidt-org/cpeabs/blob/master/src/rdkb/impl.c#L183

2021-11-23 17:53 UTC, shilpa24balaji approved these changes

2021-11-24 05:43 UTC, sadhyama approved these changes

2021-11-24 17:56 UTC, merged